spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/import
    password: password
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  main:
    banner-mode: off
server:
  port: 8081

app:
  config:
    max-order-size: 20
    main-digit-folder-path: D:\ГосАрхив\Тест\Оцифровка
    reading-room-path: D:\ГосАрхив\Тест\Читальный зал
    reader-folders-path: D:\ГосАрхив\Тест
